openapi: 3.0.0
info:
  title: P-1 Auth API
  version: 1.0.0
  description: API documentation for P-1 Authentication system
servers:
  - url: http://127.0.0.1:4321
paths:
  /api/auth/login:
    post:
      summary: Login
      description: Authenticate a user using email and password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '200':
          description: Successful login

  /api/auth/register:
    post:
      summary: Register
      description: Create a new user account.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
              required:
                - username
                - email
                - password
      responses:
        '201':
          description: User successfully registered

  /api/auth/logout:
    post:
      summary: Logout
      description: Log out the authenticated user.
      responses:
        '200':
          description: Successfully logged out

  /api/auth/send-verify-otp:
    post:
      summary: Send OTP
      description: Send a verification OTP to the user's email.
      responses:
        '200':
          description: OTP sent successfully

  /api/auth/verify-account:
    post:
      summary: Verify Account
      description: Verify the user's account using an OTP.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                otp:
                  type: string
              required:
                - otp
      responses:
        '200':
          description: Account verified successfully

  /api/auth/is-auth:
    post:
      summary: Is Authenticated
      description: Check if the user is authenticated.
      responses:
        '200':
          description: User is authenticated

  /api/auth/send-reset-otp:
    post:
      summary: Send Reset OTP
      description: Send a reset OTP to the user's email.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
              required:
                - email
      responses:
        '200':
          description: OTP sent for password reset

  /api/auth/reset-password:
    post:
      summary: Reset Password
      description: Reset the user's password using an OTP.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                otp:
                  type: string
                newPassword:
                  type: string
              required:
                - email
                - otp
                - newPassword
      responses:
        '200':
          description: Password reset successfully

  /api/auth/updateUser:
    post:
      summary: Update User
      description: Update user information such as username or password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                username:
                  type: string
                newUserName:
                  type: string
                password:
                  type: string
              required:
                - email
                - username
                - newUserName
                - password
      responses:
        '200':
          description: User information updated successfully

  /api/auth/users:
    get:
      summary: Get All Users
      description: Retrieve a list of all users.
      responses:
        '200':
          description: List of all users

  /api/auth/users/{userId}:
    get:
      summary: Get User
      description: Retrieve a specific user's information by their ID.
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User details retrieved successfully

    delete:
      summary: Delete User
      description: Delete a specific user by their ID.
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: User deleted successfully
